use anyhow::Result;
use nix::poll::{poll, PollFd, PollFlags, PollTimeout};
use nix::sys::fanotify::{FanotifyEvent, FanotifyResponse, MaskFlags, Response};
use std::collections::{BTreeMap, BTreeSet};
use std::os::fd::{AsFd, AsRawFd, BorrowedFd};
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};
use tracing::{info, warn};

use crate::config::{Config, Watch};
use crate::watcher::Watcher;

pub fn run_learn(config: &Config, duration: Duration, output: Option<&Path>) -> Result<()> {
    let watcher = Watcher::new()?;
    for w in &config.watches {
        watcher.add_watch(w)?;
        info!(name = %w.name, path = %w.path, "watching");
    }

    let path_index: Vec<(PathBuf, String)> = config
        .watches
        .iter()
        .filter_map(|w| w.resolved_path().ok().map(|p| (p, w.name.clone())))
        .collect();

    let mut seen: BTreeMap<String, BTreeSet<PathBuf>> = config
        .watches
        .iter()
        .map(|w| (w.name.clone(), BTreeSet::new()))
        .collect();

    let deadline = Instant::now() + duration;
    let fanotify_fd = watcher.group.as_fd();

    info!(secs = duration.as_secs(), "learning started — use the system normally");

    loop {
        let remaining = deadline.saturating_duration_since(Instant::now());
        if remaining.is_zero() {
            break;
        }
        let timeout_ms = remaining.as_millis().min(i32::MAX as u128) as i32;
        let mut fds = [PollFd::new(fanotify_fd, PollFlags::POLLIN)];
        match poll(&mut fds, PollTimeout::try_from(timeout_ms).unwrap())? {
            0 => break,
            _ => {}
        }
        let events = watcher.group.read_events()?;
        for ev in &events {
            handle_event(&watcher, &path_index, &mut seen, ev);
        }
    }

    info!("learning complete");
    write_output(config, &seen, output)
}

fn handle_event(
    watcher: &Watcher,
    path_index: &[(PathBuf, String)],
    seen: &mut BTreeMap<String, BTreeSet<PathBuf>>,
    ev: &FanotifyEvent,
) {
    let Some(fd) = ev.fd() else { return };

    let file_path = resolve_fd_path(fd).unwrap_or_else(|| PathBuf::from("<unknown>"));
    let pid = ev.pid();
    let mask = ev.mask();

    if let Some(watch_name) = find_watch(path_index, &file_path) {
        match read_exe(pid) {
            Some(exe) => {
                info!(watch = %watch_name, exe = %exe.display(), pid, "observed");
                seen.get_mut(watch_name).unwrap().insert(exe);
            }
            None => {
                warn!(pid, path = %file_path.display(), "exe unresolvable, skipping");
            }
        }
    }

    if mask.intersects(
        MaskFlags::FAN_OPEN_PERM | MaskFlags::FAN_ACCESS_PERM | MaskFlags::FAN_OPEN_EXEC_PERM,
    ) {
        let response = FanotifyResponse::new(fd, Response::FAN_ALLOW);
        let _ = watcher.group.write_response(response);
    }
}

fn find_watch<'a>(path_index: &'a [(PathBuf, String)], file_path: &Path) -> Option<&'a str> {
    let mut best: Option<(&str, usize)> = None;
    for (root, name) in path_index {
        if file_path.starts_with(root) {
            let len = root.as_os_str().len();
            if best.map_or(true, |(_, best_len)| len >= best_len) {
                best = Some((name, len));
            }
        }
    }
    best.map(|(name, _)| name)
}

fn write_output(
    config: &Config,
    seen: &BTreeMap<String, BTreeSet<PathBuf>>,
    output: Option<&Path>,
) -> Result<()> {
    let learned = Config {
        watches: config
            .watches
            .iter()
            .map(|w| Watch {
                name: w.name.clone(),
                path: w.path.clone(),
                allow_processes: seen[&w.name]
                    .iter()
                    .map(|p| p.to_string_lossy().into_owned())
                    .collect(),
                recursive: w.recursive,
            })
            .collect(),
    };

    let header = "# Generated by `cerbera learn`\n\
                  # Review this list before switching to enforce mode.\n\n";
    let body = toml::to_string_pretty(&learned)?;
    let content = format!("{header}{body}");

    match output {
        Some(path) => {
            std::fs::write(path, &content)?;
            info!(path = %path.display(), "written");
        }
        None => print!("{content}"),
    }
    Ok(())
}

fn resolve_fd_path(fd: BorrowedFd<'_>) -> Option<PathBuf> {
    std::fs::read_link(format!("/proc/self/fd/{}", fd.as_raw_fd())).ok()
}

fn read_exe(pid: i32) -> Option<PathBuf> {
    std::fs::read_link(format!("/proc/{pid}/exe")).ok()
}
